//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanYonetimi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApartmanYonetimiEntities : DbContext
    {
        public ApartmanYonetimiEntities()
            : base("name=ApartmanYonetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<ApartmentCleaning> ApartmentCleaning { get; set; }
        public virtual DbSet<ApartmentCleaningType> ApartmentCleaningType { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Block> Block { get; set; }
        public virtual DbSet<Collecting> Collecting { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<RenevuesCollecting_RS> RenevuesCollecting_RS { get; set; }
        public virtual DbSet<Revenues> Revenues { get; set; }
        public virtual DbSet<RevenuesType> RevenuesType { get; set; }
        public virtual DbSet<SafeType> SafeType { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<Subsistence> Subsistence { get; set; }
    }
}
