//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanYonetimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenevuesCollecting_RS
    {
        public int Id { get; set; }
        public int RevenuesId { get; set; }
        public int CollectingId { get; set; }
        public int PersonId { get; set; }
        public decimal Money { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifyUserName { get; set; }
    
        public virtual Collecting Collecting { get; set; }
        public virtual Person Person { get; set; }
        public virtual Revenues Revenues { get; set; }
    }
}
